### ISSUE TITLE
bug: notify.star:795: function "className" not defined

### ISSUE THREAD

**Issue by InTheDaylight14** [dmcavinue/tidbyt-proxy#4]
I'm using v0.0.3 of the docker container and running into this issue in the logs. 

```
022/12/30 03:22:29 http: panic serving 192.168.x.x:48902: template: notify.star:795: function "className" not defined

goroutine 6 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x7795e0, 0xc00001f510})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
html/template.Must(...)
	/usr/local/go/src/html/template/template.go:374
main.notifyHandler({0x862a28, 0xc0000d00e0}, 0xc0000f0200)
	/build/main.go:307 +0xcf7
net/http.HandlerFunc.ServeHTTP(0xc0000f0100, {0x862a28, 0xc0000d00e0}, 0xc0000e99f8)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000cc000, {0x862a28, 0xc0000d00e0}, 0xc0000f0000)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x861e20}, {0x862a28, 0xc0000d00e0}, 0xc0000f0000)
	/usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0000859a0, {0x8644c0, 0xc000073980})
	/usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
```

**Comment by InTheDaylight14** [comment]
I downloaded the html webpage and not the actual .star file... sorry
